# Global list of tech skills analyzed in the project
SKILLS = [
    "python", 
    "sql", 
    "aws", 
    "azure", 
    "docker", 
    "kubernetes", 
    "java", 
    "react", 
    "power bi", 
    "tableau", 
    "javascript",
    "typescript",
    "devops",
    "ci/cd",
    "git",
    "gcp",
    "postgresql",
    "snowflake",
    "terraform",
    "agile",
    "scrum",
    "api",
    "microservices",
    "oracle",
    "linux",
    "spark"
]